FORMAT: 1A
HOST: TBD

# Bravakin

Some Bravakin project.

## Login [/login]

### Authenticate or verify a user [GET]

If a valid access_token is not provided the requestor will be redirected
for authentication. After authentication the requestor will presented the 
same JSON reply with the addition of the access_token.

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN

+ Response 200 (application/json)

        {
            "data": {
                "id": "42",
                "username": "zbeeble",
                "full_name": "Zaphod Beeblebrox",
                "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_42_75sq_1295469061.jpg",
                "bio": "This is my bio",
                "website": "http://mygalaxy.com",
                "counts": {
                    "media": 1320,
                    "follows": 420,
                    "followed_by": 3410
                },
                "access_token": "ACCESS_TOKEN"
            }
        }


## Logout [/logout]

### Remove a user's access_token from the database [PUT]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
            
+ Response 200 (application/json)


## User details [/user]

### Get current user details [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {
                "id": "42",
                "username": "zbeeble",
                "full_name": "Zaphod Beeblebrox",
                "be_like": [ 
                    "Yahweh", 
                    "The Messiah",
                    "Godzilla"
                ],
                "like_tags": [
                    "landscape",
                    "adventure",
                ],
                "counts": {
                    "media": 1320,
                    "follows": 420,
                    "followed_by": 3410
                }
            }
        }


### Update current user "be like" and "tags" preferences [PUT]
Send an "add" object to add to the respective list ("be_like" or "like_tags").
Send a "remove" object to remove from a list.
Send an "update" object to rewrite the list.

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN

    + Body
    
            {
                "update": {
                    "be_like": [ 
                        "Yahweh", 
                        "The Messiah"
                    ]
                },
                "add": {
                    "like_tags": [
                        "beachvolley",
                        "power"
                    ]
                }
            }
        

+ Response 200 (application/json)

        {
            "data": {
                "id": "42",
                "username": "zbeeble",
                "full_name": "Zaphod Beeblebrox",
                "be_like": [ 
                    "Yahweh", 
                    "The Messiah"
                ],
                "like_tags": [
                    "landscape",
                    "adventure",
                    "beachvolley",
                    "power"
                ],
                "counts": {
                    "media": 1320,
                    "follows": 420,
                    "followed_by": 3410
                }
            }
        }

## User activity [/user/activity]

### Get current user's activity [GET]

Not implimented

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {

            }
        }


## Get media by tag [/tags/{tag_name}{?offset,size}]

+ Parameters

    + tag_name: "moto" (required) - Tag name to search
    + offset: 60 (optional, number) - result offset
    + size: 60 (optional, number) - number of results to retrieve

### Get media [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

    + Body
    
            {
                "data": [
                    {
                        "id": "424242",
                        "tags": "["moto"]",
                        "url": "",
                        "link": "http://instagr.am/z/B/",
                        "post_user": {
                            "id": "1234",
                            "username": "",
                            "full_name": "",
                            "profile_picture": "http://"
                    },
                    {
                        "id": "53",
                        "tags": "["moto"]",
                        "url": "",
                        "link": "http://instagr.am/a/B/",
                        "post_user": {
                            "id": "514",
                            "username": "",
                            "full_name": "",
                            "profile_picture": "http://"
                    }
                ]
            }
            


## Specific media [/media/{id}]

+ Parameters

    + id: 34632 (required) - Id of the specific media

### Get media details [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {

            }
        }
        
## Like media [/media/{id}/like]

+ Parameters

    + id: 34632 (required) - Id of the media to like
    
### Like a piece of media [PUT]

+ Requset (application/json)

    + Headers
    
            Authorization: Bearer ACCESS_TOKEN
            
+ Response 200 (application/json)


## Performance [/performance/{id}]

+ Parameters

    + id: 34632 (required) - Id of the specific media
    
### Get general performance statistics for media [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {
                "likes_per_hour": [
                    "2",
                    "1",
                    "3",
                    "6",
                    "4",
                    "2",
                    "42",
                    "21",
                    "1",
                    "0",
                    "1"
                ],
                "likes_per_day": [
                    "32",
                    "532"
                ]
            }
        }
        

## Performance [/performance]

### Get general performance statistics [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {
                "likes_per_hour": [
                    "2",
                    "1",
                    "3",
                    "6",
                    "4",
                    "2",
                    "42",
                    "21",
                    "1",
                    "0",
                    "1"
                ],
                "likes_per_day": [
                    "32",
                    "532"
                ]
            }
        }


## Global influence [/influence]

### Get user and associated points for mapping influence [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {
                "influenced": [
                    { 
                        "id": "1234",
                        "username": "somename",
                        "location": {
                            "latitude": 37.778720183610183,
                            "longitude": -122.3962783813477,
                            "id": "520640",
                            "street_address": "",
                            "name": "Le Truc"
                        }
                    }
                ],
            }
        }
        
## Media influence [/influence/{id}]

+ Parameters

    + id: 34632 (required) - Id of the specific media
    
### Get user and associated points for mapping influence for a piece of media [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer ACCESS_TOKEN
        
+ Response 200 (application/json)

        {
            "data": {
            
            }
        }